services:

    trinity.cache:
      class: Doctrine\Common\Cache\ApcuCache

    trinity.settings:
      class: Trinity\Bundle\SettingsBundle\Manager\SettingsManager
      arguments:
        - "@doctrine.orm.default_entity_manager"
        - "%settings_manager.defaults%"
        - "@trinity.cache"

    trinity.settings.twig:
      class: Trinity\Bundle\SettingsBundle\Twig\SettingsExtension
      arguments:
        - "@trinity.settings"
      public: false
      tags:
          - { name: twig.extension }

    admin.form_creator:
      class: AdminBundle\Services\FormCreator
      arguments:
        - "@form.factory"
        - "@router"
