services:

    trinity.logger_database:
        class: Trinity\FrameworkBundle\DatabaseLogger\DatabaseHandler
        arguments:
          - "@session"
          - "@security.token_storage"
          - "@request_stack"
          - "@trinity.logger.elastic.log.service"


    trinity.services.price_string_generator:
      class: Trinity\FrameworkBundle\Services\PriceStringGenerator
      arguments: [ "@trinity.settings","%trinity.framework.locale%"]

    trinity.twig.extension.full_price:
      class: Trinity\FrameworkBundle\Twig\FullPriceExtension
      arguments: [ "@trinity.services.price_string_generator"]
      tags:
        - { name: twig.extension }

    trinity.form_creator:
      class: Trinity\FrameworkBundle\Services\TrinityFormCreator
      arguments:
        - "@form.factory"
        - "@router"
